version: 2

sources:
  - name: vocabulary
    database: synthea_fhir
    schema: vocabulary
    tables:
      - name: concept
      - name: concept_cpt4
      - name: concept_ancestor
      - name: concept_synonym
      - name: concept_class
      - name: concept_relationship
      - name: domain
      - name: relationship
      - name: vocabulary
      - name: drug_strength
  
  - name: json
    database: synthea_fhir
    schema: json
    tables:
      - name: AllergyIntolerance
      - name: CarePlan
      - name: CareTeam
      - name: Claim
      - name: Condition
      - name: Device
      - name: DiagnosticReport
      - name: DocumentReference
      - name: Encounter
      - name: ExplanationOfBenefit
      - name: ImagingStudy
      - name: Immunization
      - name: Location
      - name: Medication
      - name: MedicationAdministration
      - name: MedicationRequest
      - name: Observation
      - name: Organization
      - name: Patient
      - name: Practitioner
      - name: PractitionerRole
      - name: Procedure
      - name: Provenance
      - name: SupplyDelivery