name: 'the_tuva_project'
version: '0.7.5'
config-version: 2
require-dbt-version: ">=1.3.0"


profile: duckdb

vars:

    claims_enabled: false
    clinical_enabled: true

    ## CCSR data mart vars
    # Set to "ip" for inpatient data or "op" for outpatient data (More info in the README)
    record_type: "ip"

    # CCSR Version numbers from HCUP
    dxccsr_version: "'2023.1'"
    prccsr_version: "'2023.1'"


    ## CMS HCC data mart vars
    # The payment_year variable has a default of the current year
    cms_hcc_payment_year: 2023

    # DO NOT CHANGE - Future logic to be added for selecting different HCC model versions
    cms_hcc_model_version: CMS-HCC-V24

    ## Quality Measures period var
    # to run quality measueres for a period other than current year, add the below variable uncommented to your project
    # quality_measures_period_end: "2020-12-31"


    ## Tuva Last Run
    # The date and timestamp of the dbt run that will populate the tuva_last_run column in all models.
    # Default timezone is UTC
    tuva_last_run: '{{ run_started_at.astimezone(modules.pytz.timezone("UTC")) }}'


model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  tuva:
    materialized: view